import Footer from '@/components/Footer';
import Navbar from '@/components/Navbar';
import ToastContainer from '@/components/ToastContainer';
import WalletContextProvider from '@/providers/WalletContextProvider';
import '@solana/wallet-adapter-react-ui/styles.css';
import type { Metadata } from 'next';
import './globals.css';

export const metadata: Metadata = {
  title: {
    template: '%s - Anchor Escrow System',
    default: 'Anchor Escrow System',
  },
  description: 'Generated by create next app',
  authors: [
    { name: 'Hussam ALDARWISH', url: 'https://github.com/hussam-aldarwish' },
  ],
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="flex min-h-screen flex-col">
        <WalletContextProvider>
          <Navbar />
          <main className="container mx-auto flex-1">{children}</main>
          <Footer />
          <ToastContainer />
        </WalletContextProvider>
      </body>
    </html>
  );
}
